public with sharing class FirstRun_Check {
    public static boolean FirstRun_QuickBidApprovalEmail = true;
    public static boolean FirstRun_LeadConvert = true;
    public static boolean firstRun_Downloads = true; 
    public static boolean FirstRun_Request_UpdateFields = true;
    public static boolean FirstRun_UpdateOpportunityLineItems = true;
    public static boolean FirstRun_afterInsertUpdate = true;
    public static boolean FirstRun_SetConversionDateOnOpp = true;
    public static boolean FirstRun_CreateCaseOnAccountingContact = true;
    public static boolean FirstRun_CreateCaseOnAccountingContactupd = true;
    public static boolean FirstRun_CreateCaseOnAccountingContactins = true;
    public static boolean FirstRun_ProcessInstallations = true;
    public static boolean FirstRun_OrderShellCreation = true;
    public static boolean FirstRun_ChannelCase_Closed = true;
    public static Map<Id, ProductRelease__c> FirstRun_UpdateServerFields = new Map<Id, ProductRelease__c>();
    public static boolean FirstRun_UpdateCSA = true; 
    public static boolean FirstRun_AccountSharing = true;
    public static boolean FirstRun_DepartmentHierarcy = true;
    public static boolean FirstRun_FlexeraAccount = true;
    public static boolean FirstRun_AutoCreateMilestones = true;
    public static boolean FirstRun_Lead_LeadClone = true;
    public static boolean FirstRun_Project_Billing_ITem = true;
    public static boolean FirstRun_TCApprover = true;
    public static boolean FirstRun_ProdHistory = true;    
    public static boolean FirstRun_assetcheck = true; 
    public static boolean FirstRun_OpportunityBeforeTrigger = true; 
    public static boolean FirstRun_checkAcuoProd = true; 
    public static boolean FirstRun_LX_WBSElementProject_BI_BU =true;   
    public static boolean FirstRun_LX_Project_BI_BU =true;
    public static boolean FirstRun_LX_Operations_trigger = true;
    public static boolean FirstRun_NotifyPMofNewProject_trigger = true;
    public static boolean FirstRun_LX_STAR_BI_BU_trigger = true;
    public static boolean FirstRun_LX_Case_trigger = true;
    public static boolean FirstRun_TimezoneUserTrigger = false;    
    public static boolean FirstRun_TimezoneContactTrigger = false;        
    
}