/*
Class Name : LX_budget_AI_AU_Test
Description : Test Class for LX_budget_AI_AU.
Created By : Maruthi Kolla (makolla@deloitte.com)
Created Date : 1-2-2014
Modification Log:
-------------------------------------------------------------------------
Developer        Date            Modification ID        Description
-------------------------------------------------------------------------
Maruthi Kolla    1-2-2014        1000                 Initial Version
*************************************************************************/
@isTest(seealldata=true)
public class LX_budget_AI_AU_test{

   public static testmethod void m1(){
       /* List<pse__Proj__c> Projects = Data_Project.createProject(1); 
        pse__Budget__c pse_budget = new pse__Budget__c(Hours__c=10,pse__Project__c=Projects[0].id,Name='Testing',pse__Amount__c=100,pse__Effective_Date__c=Date.today(),pse__Status__c='Approved');
        System.Test.StartTest();
        insert pse_budget;
        pse__Budget__c budget_update = [Select Hours__c from pse__Budget__c limit 1];
        budget_update.Hours__c = 20;
        update budget_update;
        System.Test.StopTest();*/   
    }
    

}