/*
Class Name : LX_PSEHelperClass
Description : Helper class to store the constants and the common methods used in the PSE projects
Created By : Akanksha Gupta (akagupta@deloitte.com)
Created Date : 29-9-2013
Modification Log:
-------------------------------------------------------------------------
Developer        Date            Modification ID        Description
-------------------------------------------------------------------------
Akanksha Gupta   29-9-2013        1000                   Initial Version
*************************************************************************/
public class LX_PSEHelperClass {
    public static string preSalesSupportRecordType          = 'Pre-Sales Support';
    public static string oppConstant                        = 'oppID';
    //public static string EasyEstimatePrintReleaseRecordType = 'Easy Estimate: Print Release';
    //public static string EasyEstimateWorkgroupOCRRecordType = 'Easy Estimate: Workgroup OCR';
    public static string EasyEstimateRecordType = 'NA Easy Estimate';
    public static string nooverrideConstant                 = 'nooverride';
    //public static string PreSalesSupportRecordType        = 'Pre-Sales Support';
    public static string RFI_RFP_RFQSupportRecordType       = 'RFI/RFP/RFQ Support';
    public static string BudgetEstimateRecordType           = 'Budget Estimate';
    public static string PilotRecordType                    = 'Pilot';
    public static string ProductionRecordType               = 'Production';
    public static string ImplementationRecordType           = 'Implementation';
    public static string OtherProfServRecordType            = 'Other Prof Serv';
    public static string EasyEstimatePrintReleaseRecordType   = 'Easy Estimate: Print Release';
    public static string EasyEstimateWorkgroupOCRRecordType   = 'Easy Estimate: Workgroup OCR';
    public static string US_Const                           = 'US';
    public static string YES_Const                          = 'Yes';
    public static string PREMISE_Const                      = 'Premise';
    public static string RecordType_Const                   = 'RecordType';
    public static string id_Const                           = 'id';
    public static string Badges_Const                       = 'Badges'; 
    public static string CaseSAPProjRecordType              = 'SAP Project Request';
    public static string Canada_Const                       = 'Canada';
    Public Static String Division_ISS                       = 'ISS';
    Public Static String Class_Implementation               = 'Implementation';
    Public Static String Prof_center                        = '15001';
    Public Static String Project_Category                   = 'Professional Services';
    Public Static String Case_type                          = 'Request';
    Public Static String Case_Status                        = 'New';
    Public Static String Case_impact                        = 'Group';   
    Public Static String Case_urgency                       = 'Medium';
    Public Static String Case_origin                        = 'Email';
    Public Static String Case_subject                       ='Request for Creation of SAP Project and SAP Contract';
    Public Static String Opp_SAP_Sent                       = 'Yes';
    Public Static String Opp_SAP_Status                     = 'Sent via Project';
    Public Static String Case_sap_project_subject           ='Request for SAP Project';
    Public Static String Case_WBS_request_subject           ='Request for WBS';
    Public Static String Case_WBS_origin                    = 'Cases';
    Public Static String Proj_PreSales                      = 'Pre-Sales';
    Public Static String Proj_Assessment                    = 'Assessment';
}