@isTest(seeAlldata =true)
public class LX_Test_PartnerProgramCountryMatch
 {
 /* Created By Abhishek Jain on 6/4/2013
    
   */
   
    Public Static  TestMethod void PartnerProgramCountryMatch()
    {
        /*
        Account acc = Data_Account.createAccount();
        acc.RecordTypeId = '012e00000004MCl';
        acc.LX_Geo__c = 'APAC';
        acc.LXK_Region__c = 'India';
        acc.Physical_Country__c = 'India';
        update acc;
        LX_Partner_Program__c PartnerProg = new LX_Partner_Program__c();
        PartnerProg.name = 'TestPrgram';
        PartnerProg.Country__c = 'India';
        PartnerProg.RecordTypeId = '012e00000004NB0';
        insert PartnerProg;
        LX_Program_Enrollment__c ProgramEnrol = new LX_Program_Enrollment__c();
        ProgramEnrol.LX_Account__c = acc.id;
        ProgramEnrol.Master_Program__c = PartnerProg.id;
        insert ProgramEnrol;*/
        
    }
  }