@isTest(seealldata = true)

private class Test_LX_ApprovalPendingTimeCards{
    
    static testMethod void test_ApprovalPendingTimeCards() {
    /*LX_ApprovalPendingTimeCards apt = new LX_ApprovalPendingTimeCards();
        test.startTest();
       // pse__Timecard_Header__c th = [Select id from pse__Timecard_Header__c where pse__Status__c = 'Un-Approved' limit 1]; 
       pse__Timecard_Header__c th = [Select id from pse__Timecard_Header__c where pse__Status__c = 'Submitted' limit 1];
       /* th.pse__Admin_Global_Edit__c = false;
        th.pse__Project_Methodology__c = 'LXK_SE - Admin';
        //th.pse__Resource__c = '003i000000P42aQAAR';
       // th.Sold_To__c = NULL;
        //update th;
        th.pse__Status__c = 'Submitted';
        update th;
    apt.execute();        
    test.stopTest();*/
    }

}