@isTest
public class TEST_passwordReset{

  /****************************************************************************************************************
                                             Test Method
    ******************************************************************************************************************/
   /* Public static testmethod void testMultiselectPicklist()
    {
         ResetPasswordController controller = new ResetPasswordController();
         controller.AssignPickListValues();
         controller.getAvblUsers();
         controller.getUsersInSelectList();
         List<String> parameters = new List<String>();
         User testUser = new User(LastName='Test User',isActive=true,userName='testuser@masco.com',legacy_company__c='Perceptive',email='testuser@lexmark.com',profileId=userInfo.getProfileId(),Alias='Test',Timezonesidkey='America/Los_Angeles',localesidKey='en_US',EmailencodingKey='ISO-8859-1',LanguageLocaleKey='en_US');
         insert testuser;
         parameters.add(testuser.Id);
         controller.setUsersSelected(parameters);
         controller.getUsersSelected();
         controller.addUsers();
         controller.getAvblUsers();
         controller.getUsersInSelectList();
         controller.setremoveList(parameters);
         controller.getremoveList();
         controller.removeUsers();
         try{
             controller.resetPassword();
         }catch(Exception e)
         {
             System.debug('Exception:'+e);
         }
         controller.getAvblUsers();
         controller.setUsersSelected(parameters);
         controller.addUsers();
         try{
             controller.resetPassword();
         }catch(Exception e)
         {
             System.debug('Exception:'+e);
         }
         controller.password = 'mascocorp123';
         controller.resetPassword();
    } */

}