@isTest(seeAllData=FALSE)
public class Test_LX_TestCoverageClass{

 static testmethod void testMethod1(){
         LX_TestCoverageClass testClassVar = new LX_TestCoverageClass();            
         
         }

 static testmethod void testMethod2(){
         LX_TestCoverageClass1 testClassVar = new LX_TestCoverageClass1();            
         
         }

 static testmethod void testMethod3(){
         LX_TestCoverageClass2 testClassVar = new LX_TestCoverageClass2();            
         
         }

/* static testmethod void testMethod4(){
         LX_TestCoverageClass3 testClassVar = new LX_TestCoverageClass3();            
         
         }
         static testmethod void testMethod5(){
         LX_TestCoverageClass4 testClassVar = new LX_TestCoverageClass4();            
         
         }
         static testmethod void testMethod6(){
         LX_TestCoverageClass5 testClassVar = new LX_TestCoverageClass5();            
         
         }
         static testmethod void testMethod7(){
         LX_TestCoverageClass6 testClassVar = new LX_TestCoverageClass6();            
         
         }
         static testmethod void testMethod8(){
         LX_TestCoverageClass7 testClassVar = new LX_TestCoverageClass7();            
         
         }
         
         static testmethod void testMethod9(){
         LX_TestCoverageClass8 testClassVar = new LX_TestCoverageClass8();            
         
         }*/

}